#Definition of the sort_dictionary() function which takes one dictionary as an input...
def sort_dictionary(_dict):

    #Sort the dictionary based on the age value...
    sorted_keys = sorted(_dict.keys(), key = lambda x: _dict[x][1])

    #Create one empty list called result...
    result = []

    #Use the for loop to go all sorted_keys...
    for k in sorted_keys:

        #Create tuple with name and phone number...
        _tuple = (k,_dict[k][0])

        #Append the _tuple to result list...
        result.append(_tuple)

    #Return the result...
    return result


